version: '3'

volumes:
  mysql-volume:

services:
  db:
    build:
      context: .
      dockerfile: ./infra/db/Dockerfile
    container_name: "kenshu-backend-laravel-db"
    environment:
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USERNAME}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - TZ=${TZ}
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306

  app:
    build:
      context: .
      dockerfile: ./infra/app/Dockerfile
    container_name: "kenshu-backend-laravel-web"
    depends_on:
      - db
    volumes:
      - "./src:/app"

  web:
    build:
      context: .
      dockerfile: ./infra/web/Dockerfile
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - "./src:/app"

